### openSMILE with simple ANN

In [1]:
# Importing the necessary libraries
import numpy as np
import pandas as pd
import tensorflow as tf
from imblearn.over_sampling import RandomOverSampler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [2]:
# Importing the dataset
dataset_train = pd.read_csv('DAIC_WOZ_train.csv')
dataset_test = pd.read_csv('DAIC_WOZ_test.csv')

# Check for NaN values in the entire DataFrame
nan_check = dataset_train.isnull().values.any()

if nan_check:
    # NaN values are present in the DataFrame
    print("There are NaN values in the DataFrame.")
    # To get the count of NaN values in each column, you can use:
    nan_counts = dataset_train.isnull().sum()
    print("NaN counts in each column:\n", nan_counts)
else:
    # No NaN values in the DataFrame
    print("There are no NaN values in the DataFrame.")
    
if nan_check:
    # NaN values are present in the DataFrame
    print("There are NaN values in the DataFrame.")
    # To get the count of NaN values in each column, you can use:
    nan_counts = dataset_test.isnull().sum()
    print("NaN counts in each column:\n", nan_counts)
else:
    # No NaN values in the DataFrame
    print("There are no NaN values in the DataFrame.")

There are no NaN values in the DataFrame.
There are no NaN values in the DataFrame.


In [3]:
dataset_train

File_name  F0semitoneFrom27.5Hz_sma3nz_amean  \
0     319_108.wav                          22.141134   
1     319_110.wav                          23.670998   
2     319_113.wav                          23.425415   
3     319_117.wav                          19.425419   
4     319_118.wav                          20.016453   
...           ...                                ...   
7859   485_86.wav                          27.099955   
7860   485_93.wav                          27.312315   
7861   485_95.wav                          26.755630   
7862   485_96.wav                          25.941549   
7863   485_97.wav                          25.141226   

      F0semitoneFrom27.5Hz_sma3nz_stddevNorm  \
0                                   0.082231   
1                                   0.123909   
2                                   0.098913   
3                                   0.070607   
4                                   0.048982   
...                                      ...   
7859                                0.051486   
7860                                0.040492   
7861                                0.054737   
7862                                0.041303   
7863                                0.035315   

      F0semitoneFrom27.5Hz_sma3nz_percentile20.0  \
0                                      20.151621   
1                                      21.412556   
2                                      21.303453   
3                                      18.239971   
4                                      19.311535   
...                                          ...   
7859                                   25.859745   
7860                                   26.278961   
7861                                   25.431299   
7862                                   24.938698   
7863                                   24.426844   

      F0semitoneFrom27.5Hz_sma3nz_percentile50.0  \
0                                      22.279160   
1                                      22.706928   
2                                      22.956043   
3                                      19.108694   
4                                      19.971653   
...                                          ...   
7859                                   27.048540   
7860                                   27.468130   
7861                                   26.611588   
7862                                   26.098194   
7863                                   24.861052   

      F0semitoneFrom27.5Hz_sma3nz_percentile80.0  \
0                                      23.964336   
1                                      26.246941   
2                                      24.994799   
3                                      20.066917   
4                                      20.769562   
...                                          ...   
7859                                   28.234947   
7860                                   28.221270   
7861                                   27.725195   
7862                                   26.680971   
7863                                   26.031624   

      F0semitoneFrom27.5Hz_sma3nz_pctlrange0-2  \
0                                     3.812716   
1                                     4.834385   
2                                     3.691345   
3                                     1.826946   
4                                     1.458027   
...                                        ...   
7859                                  2.375202   
7860                                  1.942308   
7861                                  2.293896   
7862                                  1.742273   
7863                                  1.604780   

      F0semitoneFrom27.5Hz_sma3nz_meanRisingSlope  \
0                                      103.089966   
1                                       95.873154   
2                                       66.809525   
3                                       67.299538   
4                

In [71]:
column_index = 89
selected_column = dataset_train.iloc[:, column_index]
print(selected_column)

0       1
1       1
2       1
3       1
4       1
       ..
7859    0
7860    0
7861    0
7862    0
7863    0
Name: Label, Length: 7864, dtype: int64


In [72]:
# Creating Dependent and Independent Variables
X_train= dataset_train.iloc[:, 1:87].values
y_train = dataset_train.iloc[:, -1].values

X_test = dataset_test.iloc[:, 1:87].values
y_test = dataset_test.iloc[:, -1].values

In [73]:
print(y.shape)

(4135,)


In [74]:
# Apply RandomOverSampler to balance the entire dataset
ros = RandomOverSampler(random_state=42)
X_resampled, y_resampled = ros.fit_resample(X, y)

In [75]:
# Feature Scaling
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [76]:
# Building the ANN
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=500, activation='relu'))
ann.add(tf.keras.layers.Dense(units=450, activation='relu'))
ann.add(tf.keras.layers.Dense(units=400, activation='relu'))
ann.add(tf.keras.layers.Dense(units=350, activation='relu'))
ann.add(tf.keras.layers.Dense(units=300, activation='relu'))
ann.add(tf.keras.layers.Dense(units=250, activation='relu'))
ann.add(tf.keras.layers.Dense(units=200, activation='relu'))
ann.add(tf.keras.layers.Dense(units=150, activation='relu'))
ann.add(tf.keras.layers.Dense(units=100, activation='relu'))
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [77]:
# Training the ANN
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
ann.fit(X_train, y_train, batch_size=200, epochs=10)

Epoch 1/10
40/40 [==============================] - 2s 11ms/step - loss: 0.5271 - accuracy: 0.7481
Epoch 2/10
40/40 [==============================] - 0s 11ms/step - loss: 0.3846 - accuracy: 0.8310
Epoch 3/10
40/40 [==============================] - 0s 11ms/step - loss: 0.2876 - accuracy: 0.8767
Epoch 4/10
40/40 [==============================] - 0s 11ms/step - loss: 0.2064 - accuracy: 0.9142
Epoch 5/10
40/40 [==============================] - 0s 11ms/step - loss: 0.1781 - accuracy: 0.9308
Epoch 6/10
40/40 [==============================] - 0s 11ms/step - loss: 0.1375 - accuracy: 0.9508
Epoch 7/10
40/40 [==============================] - 0s 11ms/step - loss: 0.1192 - accuracy: 0.9561
Epoch 8/10
40/40 [==============================] - 0s 11ms/step - loss: 0.0812 - accuracy: 0.9688
Epoch 9/10
40/40 [==============================] - 0s 11ms/step - loss: 0.0649 - accuracy: 0.9748
Epoch 10/10
40/40 [==============================] - 0s 11ms/step - loss: 0.0434 - accuracy: 0.9850


In [78]:
# Predictions
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)

130/130 [==============================] - 0s 3ms/step


In [79]:
# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

Confusion Matrix:
 [[2369  600]
 [ 896  270]]


In [80]:
# Accuracy Score
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Classification Report
report = classification_report(y_test, y_pred)
print("Classification Report:\n", report)

Accuracy: 0.6382103990326481
Classification Report:
               precision    recall  f1-score   support

           0       0.73      0.80      0.76      2969
           1       0.31      0.23      0.27      1166

    accuracy                           0.64      4135
   macro avg       0.52      0.51      0.51      4135
weighted avg       0.61      0.64      0.62      4135



### Using Autoencoder

In [47]:
# Importing the necessary libraries
import numpy as np
import pandas as pd
import tensorflow as tf
from imblearn.over_sampling import RandomOverSampler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

# Importing the dataset
dataset_train = pd.read_csv('DAIC_WOZ_train.csv')
dataset_test = pd.read_csv('DAIC_WOZ_test.csv')

# Check for NaN values in the entire DataFrame
nan_check = dataset_train.isnull().values.any()

if nan_check:
    # NaN values are present in the DataFrame
    print("There are NaN values in the DataFrame.")
    # To get the count of NaN values in each column, you can use:
    nan_counts = dataset_train.isnull().sum()
    print("NaN counts in each column:\n", nan_counts)
else:
    # No NaN values in the DataFrame
    print("There are no NaN values in the DataFrame.")
    
if nan_check:
    # NaN values are present in the DataFrame
    print("There are NaN values in the DataFrame.")
    # To get the count of NaN values in each column, you can use:
    nan_counts = dataset_test.isnull().sum()
    print("NaN counts in each column:\n", nan_counts)
else:
    # No NaN values in the DataFrame
    print("There are no NaN values in the DataFrame.")

# Creating Dependent and Independent Variables
X_train = dataset_train.iloc[:, 1:89].values
y_train = dataset_train.iloc[:, -1].values

X_test = dataset_test.iloc[:, 1:89].values
y_test = dataset_test.iloc[:, -1].values

# Apply RandomOverSampler to balance the entire dataset
ros = RandomOverSampler(random_state=42)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)

# Feature Scaling
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Autoencoder
input_dim = X_train.shape[1]
latent_dim = 88  # Choose the desired dimension for the latent space

autoencoder = tf.keras.models.Sequential()
autoencoder.add(tf.keras.layers.Dense(units=64, activation='relu', input_dim=input_dim))
autoencoder.add(tf.keras.layers.Dense(units=latent_dim, activation='relu'))

autoencoder.compile(optimizer='adam', loss='mean_squared_error')
autoencoder.fit(X_train, X_train, epochs=50, batch_size=32, shuffle=True, validation_data=(X_test, X_test))

# Extract the encoder part of the autoencoder
encoder = tf.keras.models.Sequential()
encoder.add(autoencoder.layers[0])
encoder.add(autoencoder.layers[1])

# Encode the training and test sets
X_train_encoded = encoder.predict(X_train)
X_test_encoded = encoder.predict(X_test)

# Building the ANN on top of the encoded data
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=50, activation='relu', input_dim=latent_dim))
ann.add(tf.keras.layers.Dense(units=45, activation='relu'))
ann.add(tf.keras.layers.Dense(units=40, activation='relu'))
ann.add(tf.keras.layers.Dense(units=35, activation='relu'))
ann.add(tf.keras.layers.Dense(units=30, activation='relu'))
ann.add(tf.keras.layers.Dense(units=25, activation='relu'))
ann.add(tf.keras.layers.Dense(units=20, activation='relu'))
ann.add(tf.keras.layers.Dense(units=15, activation='relu'))
ann.add(tf.keras.layers.Dense(units=10, activation='relu'))
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Training the ANN
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
ann.fit(X_train_encoded, y_train, batch_size=200, epochs=100)

# Predictions
y_pred = ann.predict(X_test_encoded)
y_pred = (y_pred > 0.5)

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

# Accuracy Score
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Classification Report
report = classification_report(y_test, y_pred)
print("Classification Report:\n", report)


There are no NaN values in the DataFrame.
There are no NaN values in the DataFrame.
Epoch 1/50
246/246 [==============================] - 1s 2ms/step - loss: 0.8413 - val_loss: 1.1926
Epoch 2/50
246/246 [==============================] - 0s 2ms/step - loss: 0.6686 - val_loss: 1.0248
Epoch 3/50
246/246 [==============================] - 0s 2ms/step - loss: 0.6221 - val_loss: 0.9077
Epoch 4/50
246/246 [==============================] - 0s 2ms/step - loss: 0.5978 - val_loss: 0.8144
Epoch 5/50
246/246 [==============================] - 0s 2ms/step - loss: 0.5815 - val_loss: 0.7468
Epoch 6/50
246/246 [==============================] - 0s 2ms/step - loss: 0.5690 - val_loss: 0.7089
Epoch 7/50
246/246 [==============================] - 0s 2ms/step - loss: 0.5601 - val_loss: 0.6864
Epoch 8/50
246/246 [==============================] - 0s 2ms/step - loss: 0.5535 - val_loss: 0.6719
Epoch 9/50
246/246 [==============================] - 0s 2ms/step - loss: 0.5480 - val_loss: 0.6623
Epoch 10/50
246/

In [50]:
# Importing the necessary libraries
import numpy as np
import pandas as pd
import tensorflow as tf
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

# Importing the dataset
dataset_train = pd.read_csv('DAIC_WOZ_train.csv')
dataset_test = pd.read_csv('DAIC_WOZ_test.csv')

# Check for NaN values in the entire DataFrame
nan_check = dataset_train.isnull().values.any()

if nan_check:
    # NaN values are present in the DataFrame
    print("There are NaN values in the DataFrame.")
    # To get the count of NaN values in each column, you can use:
    nan_counts = dataset_train.isnull().sum()
    print("NaN counts in each column:\n", nan_counts)
else:
    # No NaN values in the DataFrame
    print("There are no NaN values in the DataFrame.")
    
if nan_check:
    # NaN values are present in the DataFrame
    print("There are NaN values in the DataFrame.")
    # To get the count of NaN values in each column, you can use:
    nan_counts = dataset_test.isnull().sum()
    print("NaN counts in each column:\n", nan_counts)
else:
    # No NaN values in the DataFrame
    print("There are no NaN values in the DataFrame.")

# Creating Dependent and Independent Variables
X_train = dataset_train.iloc[:, 1:88].values
y_train = dataset_train.iloc[:, -1].values

X_test = dataset_test.iloc[:, 1:88].values
y_test = dataset_test.iloc[:, -1].values

# Apply SMOTE to balance the entire dataset
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X_train, y_train)

# Feature Scaling
sc = StandardScaler()
X_train = sc.fit_transform(X_resampled)  # Use resampled data for training
X_test = sc.transform(X_test)

# Autoencoder
input_dim = X_train.shape[1]
latent_dim = 87  # Choose the desired dimension for the latent space

autoencoder = tf.keras.models.Sequential()
autoencoder.add(tf.keras.layers.Dense(units=64, activation='relu', input_dim=input_dim))
autoencoder.add(tf.keras.layers.Dense(units=latent_dim, activation='relu'))

autoencoder.compile(optimizer='adam', loss='mean_squared_error')
autoencoder.fit(X_train, X_train, epochs=50, batch_size=32, shuffle=True, validation_data=(X_test, X_test))

# Extract the encoder part of the autoencoder
encoder = tf.keras.models.Sequential()
encoder.add(autoencoder.layers[0])
encoder.add(autoencoder.layers[1])

# Encode the training and test sets
X_train_encoded = encoder.predict(X_train)
X_test_encoded = encoder.predict(X_test)

# Building the ANN on top of the encoded data
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=50, activation='relu', input_dim=latent_dim))
ann.add(tf.keras.layers.Dense(units=45, activation='relu'))
ann.add(tf.keras.layers.Dense(units=40, activation='relu'))
ann.add(tf.keras.layers.Dense(units=35, activation='relu'))
ann.add(tf.keras.layers.Dense(units=30, activation='relu'))
ann.add(tf.keras.layers.Dense(units=25, activation='relu'))
ann.add(tf.keras.layers.Dense(units=20, activation='relu'))
ann.add(tf.keras.layers.Dense(units=15, activation='relu'))
ann.add(tf.keras.layers.Dense(units=10, activation='relu'))
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Training the ANN
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
ann.fit(X_train_encoded, y_resampled, batch_size=32, epochs=100)  # Use resampled labels for training

# Predictions
y_pred = ann.predict(X_test_encoded)
y_pred = (y_pred > 0.5)

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

# Accuracy Score
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Classification Report
report = classification_report(y_test, y_pred)
print("Classification Report:\n", report)


There are no NaN values in the DataFrame.
There are no NaN values in the DataFrame.
Epoch 1/50
363/363 [==============================] - 1s 2ms/step - loss: 0.8006 - val_loss: 1.4851
Epoch 2/50
363/363 [==============================] - 0s 1ms/step - loss: 0.6419 - val_loss: 1.3654
Epoch 3/50
363/363 [==============================] - 0s 1ms/step - loss: 0.5945 - val_loss: 1.2918
Epoch 4/50
363/363 [==============================] - 0s 1ms/step - loss: 0.5710 - val_loss: 1.2402
Epoch 5/50
363/363 [==============================] - 0s 1ms/step - loss: 0.5546 - val_loss: 1.1997
Epoch 6/50
363/363 [==============================] - 1s 1ms/step - loss: 0.5432 - val_loss: 1.1733
Epoch 7/50
363/363 [==============================] - 1s 1ms/step - loss: 0.5346 - val_loss: 1.1520
Epoch 8/50
363/363 [==============================] - 0s 1ms/step - loss: 0.5282 - val_loss: 1.1397
Epoch 9/50
363/363 [==============================] - 0s 1ms/step - loss: 0.5197 - val_loss: 1.1306
Epoch 10/50
363/

In [51]:
# Importing the necessary libraries
import numpy as np
import pandas as pd
import tensorflow as tf
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

# Importing the dataset
dataset_train = pd.read_csv('DAIC_WOZ_train.csv')
dataset_test = pd.read_csv('DAIC_WOZ_test.csv')

# Check for NaN values in the entire DataFrame
nan_check = dataset_train.isnull().values.any()

if nan_check:
    # NaN values are present in the DataFrame
    print("There are NaN values in the DataFrame.")
    # To get the count of NaN values in each column, you can use:
    nan_counts = dataset_train.isnull().sum()
    print("NaN counts in each column:\n", nan_counts)
else:
    # No NaN values in the DataFrame
    print("There are no NaN values in the DataFrame.")
    
if nan_check:
    # NaN values are present in the DataFrame
    print("There are NaN values in the DataFrame.")
    # To get the count of NaN values in each column, you can use:
    nan_counts = dataset_test.isnull().sum()
    print("NaN counts in each column:\n", nan_counts)
else:
    # No NaN values in the DataFrame
    print("There are no NaN values in the DataFrame.")

# Creating Dependent and Independent Variables
X_train = dataset_train.iloc[:, 1:88].values
y_train = dataset_train.iloc[:, -1].values

X_test = dataset_test.iloc[:, 1:88].values
y_test = dataset_test.iloc[:, -1].values

# Apply SMOTE to balance the entire dataset
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X_train, y_train)

# Feature Scaling
sc = StandardScaler()
X_train = sc.fit_transform(X_resampled)  # Use resampled data for training

# Apply SMOTE to the test set
X_test_resampled, y_test_resampled = smote.fit_resample(X_test, y_test)
X_test = sc.transform(X_test_resampled)  # Use resampled data for testing

# Autoencoder
input_dim = X_train.shape[1]
latent_dim = 87  # Choose the desired dimension for the latent space

autoencoder = tf.keras.models.Sequential()
autoencoder.add(tf.keras.layers.Dense(units=64, activation='relu', input_dim=input_dim))
autoencoder.add(tf.keras.layers.Dense(units=latent_dim, activation='relu'))

autoencoder.compile(optimizer='adam', loss='mean_squared_error')
autoencoder.fit(X_train, X_train, epochs=50, batch_size=32, shuffle=True, validation_data=(X_test, X_test))

# Extract the encoder part of the autoencoder
encoder = tf.keras.models.Sequential()
encoder.add(autoencoder.layers[0])
encoder.add(autoencoder.layers[1])

# Encode the training and test sets
X_train_encoded = encoder.predict(X_train)
X_test_encoded = encoder.predict(X_test)

# Building the ANN on top of the encoded data
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=50, activation='relu', input_dim=latent_dim))
ann.add(tf.keras.layers.Dense(units=45, activation='relu'))
ann.add(tf.keras.layers.Dense(units=40, activation='relu'))
ann.add(tf.keras.layers.Dense(units=35, activation='relu'))
ann.add(tf.keras.layers.Dense(units=30, activation='relu'))
ann.add(tf.keras.layers.Dense(units=25, activation='relu'))
ann.add(tf.keras.layers.Dense(units=20, activation='relu'))
ann.add(tf.keras.layers.Dense(units=15, activation='relu'))
ann.add(tf.keras.layers.Dense(units=10, activation='relu'))
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Training the ANN
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
ann.fit(X_train_encoded, y_resampled, batch_size=32, epochs=50)  # Use resampled labels for training

# Predictions
y_pred = ann.predict(X_test_encoded)
y_pred = (y_pred > 0.5)

# Confusion Matrix
cm = confusion_matrix(y_test_resampled, y_pred)
print("Confusion Matrix:\n", cm)

# Accuracy Score
accuracy = accuracy_score(y_test_resampled, y_pred)
print("Accuracy:", accuracy)

# Classification Report
report = classification_report(y_test_resampled, y_pred)
print("Classification Report:\n", report)


There are no NaN values in the DataFrame.
There are no NaN values in the DataFrame.
Epoch 1/50
363/363 [==============================] - 1s 2ms/step - loss: 0.8136 - val_loss: 1.3782
Epoch 2/50
363/363 [==============================] - 1s 1ms/step - loss: 0.6353 - val_loss: 1.2662
Epoch 3/50
363/363 [==============================] - 1s 2ms/step - loss: 0.5914 - val_loss: 1.2168
Epoch 4/50
363/363 [==============================] - 1s 1ms/step - loss: 0.5730 - val_loss: 1.1735
Epoch 5/50
363/363 [==============================] - 1s 1ms/step - loss: 0.5607 - val_loss: 1.1435
Epoch 6/50
363/363 [==============================] - 1s 1ms/step - loss: 0.5521 - val_loss: 1.1231
Epoch 7/50
363/363 [==============================] - 1s 1ms/step - loss: 0.5455 - val_loss: 1.1126
Epoch 8/50
363/363 [==============================] - 1s 1ms/step - loss: 0.5408 - val_loss: 1.1031
Epoch 9/50
363/363 [==============================] - 1s 1ms/step - loss: 0.5374 - val_loss: 1.0989
Epoch 10/50
363/

In [54]:
from sklearn.ensemble import RandomForestClassifier

# Assuming X_train and y_train are your training data
model = RandomForestClassifier()
model.fit(X_train, y_train)

feature_importance = model.feature_importances_


[0.0060366  0.00614507 0.00630926 0.00634151 0.00643437 0.00646951
 0.00676894 0.00685088 0.00705373 0.00726135 0.00726744 0.00739975
 0.00758236 0.00759401 0.00765314 0.0077608  0.00777934 0.00790211
 0.00798548 0.00809857 0.00827585 0.00828164 0.00834856 0.0083778
 0.00846896 0.00848755 0.00863954 0.00882271 0.0090502  0.00911052
 0.00914255 0.00922206 0.00933797 0.009382   0.00952699 0.00953337
 0.00962587 0.00964413 0.00967316 0.00968844 0.00979281 0.00999238
 0.01012931 0.01024227 0.01030491 0.0103765  0.01048768 0.01054583
 0.01088293 0.01100951 0.0110399  0.01119715 0.01123011 0.01129948
 0.01139749 0.01148032 0.01175368 0.01176623 0.01187568 0.0119732
 0.01198574 0.01205722 0.0121124  0.01215384 0.01220979 0.0130909
 0.01311438 0.01311543 0.01347931 0.01395191 0.01401383 0.01413517
 0.01487954 0.01493237 0.01529745 0.01560094 0.01573424 0.01666304
 0.01686039 0.01833123 0.01914955 0.01969136 0.01994816 0.02055704
 0.02149694 0.0224976  0.02380345 0.0270253 ]


In [59]:
from sklearn.ensemble import RandomForestClassifier
import numpy as np

# Assuming X_train and y_train are your training data
model = RandomForestClassifier()
model.fit(X_train, y_train)

feature_importance = model.feature_importances_

# Get the indices of the most important features in descending order
most_important_indices = np.argsort(feature_importance)[::-1]

# Print the indices of the top features
print("Indices of the most important features:", most_important_indices)


Indices of the most important features: [ 2  3 62  0 60 36  4 34 38 52 68 28 35 65 77 54 32 29 76  5 64 53 30 21
 12 69 79 22 72 37 26 74 41 40 33 75 58 71 42 11 80 46 24 73 27  1 67 25
 48 63 78 70 61 59 47 23 39 55 66 18 31  8  6 83 84 81 20 16  9 82  7 86
 43 10 17 15 49 13 19 87 45 85 56 44 51 14 57 50]


### Using ML Classifiers

In [82]:
# Importing the necessary libraries
import numpy as np
import pandas as pd
from imblearn.over_sampling import RandomOverSampler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

# Importing the dataset
dataset_train = pd.read_csv('DAIC_WOZ_train.csv')
dataset_test = pd.read_csv('DAIC_WOZ_test.csv')

# Check for NaN values in the entire DataFrame
nan_check_train = dataset_train.isnull().values.any()
nan_check_test = dataset_test.isnull().values.any()

if nan_check_train:
    print("There are NaN values in the training dataset.")
    nan_counts = dataset_train.isnull().sum()
    print("NaN counts in each column of training dataset:\n", nan_counts)
else:
    print("There are no NaN values in the training dataset.")

if nan_check_test:
    print("There are NaN values in the test dataset.")
    nan_counts = dataset_test.isnull().sum()
    print("NaN counts in each column of test dataset:\n", nan_counts)
else:
    print("There are no NaN values in the test dataset.")

# Creating Dependent and Independent Variables
X_train = dataset_train.iloc[:, 1:88].values
y_train = dataset_train.iloc[:, -1].values

X_test = dataset_test.iloc[:, 1:88].values
y_test = dataset_test.iloc[:, -1].values

# Apply RandomOverSampler to balance the entire dataset
ros = RandomOverSampler(random_state=42)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)

# Feature Scaling
sc = StandardScaler()
X_train = sc.fit_transform(X_resampled)
X_test = sc.transform(X_test)

# Support Vector Machine (SVM)
svm_classifier = SVC(kernel='rbf', random_state=42)
svm_classifier.fit(X_train, y_resampled)
svm_y_pred = svm_classifier.predict(X_test)

# Random Forest
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
rf_classifier.fit(X_train, y_resampled)
rf_y_pred = rf_classifier.predict(X_test)

# Decision Trees
dt_classifier = DecisionTreeClassifier(random_state=42)
dt_classifier.fit(X_train, y_resampled)
dt_y_pred = dt_classifier.predict(X_test)

# Logistic Regression
lr_classifier = LogisticRegression(random_state=42)
lr_classifier.fit(X_train, y_resampled)
lr_y_pred = lr_classifier.predict(X_test)

# Evaluate each classifier
classifiers = {'SVM': svm_y_pred, 'Random Forest': rf_y_pred, 'Decision Trees': dt_y_pred, 'Logistic Regression': lr_y_pred}

for clf_name, clf_y_pred in classifiers.items():
    # Confusion Matrix
    cm = confusion_matrix(y_test, clf_y_pred)
    print(f"{clf_name} Confusion Matrix:\n", cm)

    # Accuracy Score
    accuracy = accuracy_score(y_test, clf_y_pred)
    print(f"{clf_name} Accuracy:", accuracy)

    # Classification Report
    report = classification_report(y_test, clf_y_pred)
    print(f"{clf_name} Classification Report:\n", report)
    print("="*50)


There are no NaN values in the training dataset.
There are no NaN values in the test dataset.
SVM Confusion Matrix:
 [[1581 1388]
 [ 511  655]]
SVM Accuracy: 0.5407496977025393
SVM Classification Report:
               precision    recall  f1-score   support

           0       0.76      0.53      0.62      2969
           1       0.32      0.56      0.41      1166

    accuracy                           0.54      4135
   macro avg       0.54      0.55      0.52      4135
weighted avg       0.63      0.54      0.56      4135

Random Forest Confusion Matrix:
 [[2405  564]
 [ 919  247]]
Random Forest Accuracy: 0.641354292623942
Random Forest Classification Report:
               precision    recall  f1-score   support

           0       0.72      0.81      0.76      2969
           1       0.30      0.21      0.25      1166

    accuracy                           0.64      4135
   macro avg       0.51      0.51      0.51      4135
weighted avg       0.61      0.64      0.62      4135

D

## DAIC_WOZ with openSMILE features of 88 Dimensional feature vector using a simple ANN structure for classification. Here, training data is being balanced using random over sampling and test data is kept as it is. Standardization of features is being used.

In [83]:
# Importing the necessary libraries
import numpy as np
import pandas as pd
import tensorflow as tf
from imblearn.over_sampling import RandomOverSampler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

# Importing the dataset
dataset_train = pd.read_csv('DAIC_WOZ_train.csv')
dataset_test = pd.read_csv('DAIC_WOZ_test.csv')

# Check for NaN values in the entire DataFrame
nan_check = dataset_train.isnull().values.any()

if nan_check:
    # NaN values are present in the DataFrame
    print("There are NaN values in the DataFrame.")
    # To get the count of NaN values in each column, you can use:
    nan_counts = dataset_train.isnull().sum()
    print("NaN counts in each column:\n", nan_counts)
else:
    # No NaN values in the DataFrame
    print("There are no NaN values in the DataFrame.")
    
if nan_check:
    # NaN values are present in the DataFrame
    print("There are NaN values in the DataFrame.")
    # To get the count of NaN values in each column, you can use:
    nan_counts = dataset_test.isnull().sum()
    print("NaN counts in each column:\n", nan_counts)
else:
    # No NaN values in the DataFrame
    print("There are no NaN values in the DataFrame.")

There are no NaN values in the DataFrame.
There are no NaN values in the DataFrame.


In [91]:
# Creating Dependent and Independent Variables
X_train = dataset_train.iloc[:, 1:89].values
y_train = dataset_train.iloc[:, -1].values

X_test = dataset_test.iloc[:, 1:89].values
y_test = dataset_test.iloc[:, -1].values

In [92]:
np.shape(X_train)

(7864, 88)

In [93]:
np.shape(y_train)

(7864,)

In [94]:
y_train

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [97]:
print(np.shape(X_test))
print(np.shape(y_test))
print(y_test)

(4135, 88)
(4135,)
[1 1 1 ... 0 0 0]


In [100]:
# Apply RandomOverSampler to balance the entire dataset
ros = RandomOverSampler(random_state=42)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)

In [102]:
print(np.shape(X_resampled))
print(np.shape(y_resampled))

(11588, 88)
(11588,)


In [103]:
np.bincount(y_resampled)

array([5794, 5794], dtype=int64)

In [104]:
# Feature Scaling
sc = StandardScaler()
X_train = sc.fit_transform(X_resampled)
X_test = sc.transform(X_test)

In [105]:
# Building the ANN
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=50, activation='relu'))
ann.add(tf.keras.layers.Dense(units=45, activation='relu'))
ann.add(tf.keras.layers.Dense(units=40, activation='relu'))
ann.add(tf.keras.layers.Dense(units=35, activation='relu'))
ann.add(tf.keras.layers.Dense(units=30, activation='relu'))
ann.add(tf.keras.layers.Dense(units=25, activation='relu'))
ann.add(tf.keras.layers.Dense(units=20, activation='relu'))
ann.add(tf.keras.layers.Dense(units=15, activation='relu'))
ann.add(tf.keras.layers.Dense(units=10, activation='relu'))
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [110]:
# Training the ANN
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
ann.fit(X_resampled, y_resampled, batch_size=32, epochs=250)

Epoch 1/250
363/363 [==============================] - 2s 1ms/step - loss: 0.2543 - accuracy: 0.8937
Epoch 2/250
363/363 [==============================] - 1s 1ms/step - loss: 0.2503 - accuracy: 0.8969
Epoch 3/250
363/363 [==============================] - 1s 1ms/step - loss: 0.2588 - accuracy: 0.8918
Epoch 4/250
363/363 [==============================] - 1s 1ms/step - loss: 0.2577 - accuracy: 0.8947
Epoch 5/250
363/363 [==============================] - 1s 1ms/step - loss: 0.2806 - accuracy: 0.8833
Epoch 6/250
363/363 [==============================] - 1s 1ms/step - loss: 0.2671 - accuracy: 0.8889
Epoch 7/250
363/363 [==============================] - 1s 1ms/step - loss: 0.2446 - accuracy: 0.8985
Epoch 8/250
363/363 [==============================] - 1s 1ms/step - loss: 0.2687 - accuracy: 0.8850
Epoch 9/250
363/363 [==============================] - 1s 1ms/step - loss: 0.2481 - accuracy: 0.8932
Epoch 10/250
363/363 [==============================] - 1s 1ms/step - loss: 0.2533 - accura

In [121]:
# Predictions
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)

# Accuracy Score
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Classification Report
report = classification_report(y_test, y_pred)
print("Classification Report:\n", report)

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

130/130 [==============================] - 0s 867us/step
Accuracy: 0.5753325272067714
Classification Report:
               precision    recall  f1-score   support

           0       0.74      0.63      0.68      2969
           1       0.31      0.43      0.36      1166

    accuracy                           0.58      4135
   macro avg       0.53      0.53      0.52      4135
weighted avg       0.62      0.58      0.59      4135

Confusion Matrix:
 [[1883 1086]
 [ 670  496]]


## DAIC_WOZ with openSMILE features of 88 Dimensional feature vector using a simple ANN structure for classification. Here, training data is being balanced using random over sampling and test data is kept as it is. Normalization of features is being used.

### !st Model

In [451]:
# Importing the necessary libraries
import numpy as np
import pandas as pd
import tensorflow as tf
from imblearn.over_sampling import RandomOverSampler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

# Importing the dataset
dataset_train = pd.read_csv('DAIC_WOZ_train.csv')
dataset_test = pd.read_csv('DAIC_WOZ_test.csv')

# Check for NaN values in the entire DataFrame
nan_check = dataset_train.isnull().values.any()

if nan_check:
    # NaN values are present in the DataFrame
    print("There are NaN values in the DataFrame.")
    # To get the count of NaN values in each column, you can use:
    nan_counts = dataset_train.isnull().sum()
    print("NaN counts in each column:\n", nan_counts)
else:
    # No NaN values in the DataFrame
    print("There are no NaN values in the DataFrame.")
    
if nan_check:
    # NaN values are present in the DataFrame
    print("There are NaN values in the DataFrame.")
    # To get the count of NaN values in each column, you can use:
    nan_counts = dataset_test.isnull().sum()
    print("NaN counts in each column:\n", nan_counts)
else:
    # No NaN values in the DataFrame
    print("There are no NaN values in the DataFrame.")
    
# Creating Dependent and Independent Variables
X_train = dataset_train.iloc[:, 1:89].values
y_train = dataset_train.iloc[:, -1].values

X_test = dataset_test.iloc[:, 1:89].values
y_test = dataset_test.iloc[:, -1].values

# # Apply RandomOverSampler to balance the entire dataset
ros = RandomOverSampler(random_state=55)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)


There are no NaN values in the DataFrame.
There are no NaN values in the DataFrame.


In [452]:
print(np.shape(X_resampled))

(11588, 88)


In [453]:
print(np.shape(X_test))

(4135, 88)


In [454]:
nan_counts = dataset_test.isnull().sum()
nan_counts

File_name                                     0
F0semitoneFrom27.5Hz_sma3nz_amean             0
F0semitoneFrom27.5Hz_sma3nz_stddevNorm        0
F0semitoneFrom27.5Hz_sma3nz_percentile20.0    0
F0semitoneFrom27.5Hz_sma3nz_percentile50.0    0
                                             ..
StddevVoicedSegmentLengthSec                  0
MeanUnvoicedSegmentLength                     0
StddevUnvoicedSegmentLength                   0
equivalentSoundLevel_dBp                      0
Label                                         0
Length: 90, dtype: int64

In [458]:
# Feature Normalization
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler(feature_range = (0,1))
X_train_resampled = sc.fit_transform(X_resampled)
# X_test = sc.transform(X_test)

In [459]:
print(X_train_resampled)

[[0.49850855 0.14409865 0.46505167 ... 0.03735632 0.03597636 0.8159468 ]
 [0.53295349 0.21713302 0.49415105 ... 0.03591954 0.0363451  0.67482642]
 [0.52742419 0.17333098 0.49163323 ... 0.05254516 0.07556342 0.74574235]
 ...
 [0.48811618 0.26343592 0.45384487 ... 0.09318554 0.18569307 0.56501844]
 [0.82676712 0.23120983 0.84914314 ... 0.03627874 0.05623627 0.72757594]
 [0.60276662 0.16672213 0.56823406 ... 0.04343501 0.06412134 0.63254801]]


In [460]:
print(np.shape(X_resampled))
print(np.shape(y_test))

(11588, 88)
(4135,)


In [461]:
ann = tf.keras.models.Sequential([
    tf.keras.layers.Dense(units=64, activation='relu', input_dim=88),
    tf.keras.layers.Dense(units=48, activation='relu'),
    tf.keras.layers.Dense(units=32, activation='relu'),
    tf.keras.layers.Dense(units=16, activation='relu'),
    tf.keras.layers.Dense(units=16, activation='relu'),
    tf.keras.layers.Dense(units=32, activation='relu'),
    tf.keras.layers.Dense(units=48, activation='relu'),
    tf.keras.layers.Dense(units=64, activation='relu'),
    tf.keras.layers.Dense(units=1, activation='sigmoid')
])

In [462]:
# Training the ANN
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
ann.fit(X_train_resampled, y_resampled, batch_size=128, epochs=50, shuffle = True)

Epoch 1/50
91/91 [==============================] - 1s 2ms/step - loss: 0.6753 - accuracy: 0.5826
Epoch 2/50
91/91 [==============================] - 0s 2ms/step - loss: 0.6502 - accuracy: 0.6239
Epoch 3/50
91/91 [==============================] - 0s 2ms/step - loss: 0.6335 - accuracy: 0.6468
Epoch 4/50
91/91 [==============================] - 0s 2ms/step - loss: 0.6113 - accuracy: 0.6759
Epoch 5/50
91/91 [==============================] - 0s 2ms/step - loss: 0.6026 - accuracy: 0.6808
Epoch 6/50
91/91 [==============================] - 0s 2ms/step - loss: 0.5978 - accuracy: 0.6851
Epoch 7/50
91/91 [==============================] - 0s 2ms/step - loss: 0.5642 - accuracy: 0.7111
Epoch 8/50
91/91 [==============================] - 0s 2ms/step - loss: 0.5711 - accuracy: 0.7059
Epoch 9/50
91/91 [==============================] - 0s 2ms/step - loss: 0.5364 - accuracy: 0.7339
Epoch 10/50
91/91 [==============================] - 0s 2ms/step - loss: 0.5252 - accuracy: 0.7436
Epoch 11/50
91/91 [

In [464]:
# Predictions
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5).astype(int)

# Accuracy Score
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Classification Report
report = classification_report(y_test, y_pred)
print("Classification Report:\n", report)

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

130/130 [==============================] - 0s 870us/step
Accuracy: 0.517291414752116
Classification Report:
               precision    recall  f1-score   support

           0       0.71      0.56      0.62      2969
           1       0.27      0.42      0.33      1166

    accuracy                           0.52      4135
   macro avg       0.49      0.49      0.48      4135
weighted avg       0.59      0.52      0.54      4135

Confusion Matrix:
 [[1649 1320]
 [ 676  490]]


### 2nd Model

In [424]:
# Importing the necessary libraries
import numpy as np
import pandas as pd
import tensorflow as tf
from imblearn.over_sampling import RandomOverSampler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

# Importing the dataset
dataset_train = pd.read_csv('DAIC_WOZ_train.csv')
dataset_test = pd.read_csv('DAIC_WOZ_test.csv')

# Check for NaN values in the entire DataFrame
nan_check = dataset_train.isnull().values.any()

if nan_check:
    # NaN values are present in the DataFrame
    print("There are NaN values in the DataFrame.")
    # To get the count of NaN values in each column, you can use:
    nan_counts = dataset_train.isnull().sum()
    print("NaN counts in each column:\n", nan_counts)
else:
    # No NaN values in the DataFrame
    print("There are no NaN values in the DataFrame.")
    
if nan_check:
    # NaN values are present in the DataFrame
    print("There are NaN values in the DataFrame.")
    # To get the count of NaN values in each column, you can use:
    nan_counts = dataset_test.isnull().sum()
    print("NaN counts in each column:\n", nan_counts)
else:
    # No NaN values in the DataFrame
    print("There are no NaN values in the DataFrame.")
    
# Creating Dependent and Independent Variables
X_train = dataset_train.iloc[:, 1:89].values
y_train = dataset_train.iloc[:, -1].values

X_test = dataset_test.iloc[:, 1:89].values
y_test = dataset_test.iloc[:, -1].values

# # Apply RandomOverSampler to balance the entire dataset
ros = RandomOverSampler(random_state=42)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)


There are no NaN values in the DataFrame.
There are no NaN values in the DataFrame.


In [425]:
# Feature Normalization
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler(feature_range = (0,1))
X_train_resampled = sc.fit_transform(X_resampled)
X_test_resampled = sc.transform(X_test)

In [435]:
print(np.shape(X_resampled))
print(np.shape(y_test))
print(np.shape(X_test))

(11588, 88)
(4135,)
(4135, 88)


In [427]:
ann = tf.keras.models.Sequential([
    tf.keras.layers.Dense(units=64, activation='relu', input_dim=88),
    tf.keras.layers.Dense(units=48, activation='relu'),
    tf.keras.layers.Dense(units=32, activation='relu'),
    tf.keras.layers.Dense(units=16, activation='relu'),
    tf.keras.layers.Dense(units=16, activation='relu'),
    tf.keras.layers.Dense(units=32, activation='relu'),
    tf.keras.layers.Dense(units=48, activation='relu'),
    tf.keras.layers.Dense(units=64, activation='relu'),
    tf.keras.layers.Dense(units=1, activation='sigmoid')
])

In [434]:
# Training the ANN
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
ann.fit(X_train_resampled, y_resampled, batch_size=128, epochs=50, shuffle = True)

Epoch 1/50
91/91 [==============================] - 1s 2ms/step - loss: 0.0514 - accuracy: 0.9820
Epoch 2/50
91/91 [==============================] - 0s 2ms/step - loss: 0.0379 - accuracy: 0.9865
Epoch 3/50
91/91 [==============================] - 0s 2ms/step - loss: 0.0502 - accuracy: 0.9827
Epoch 4/50
91/91 [==============================] - 0s 2ms/step - loss: 0.0186 - accuracy: 0.9940
Epoch 5/50
91/91 [==============================] - 0s 2ms/step - loss: 0.0725 - accuracy: 0.9752
Epoch 6/50
91/91 [==============================] - 0s 2ms/step - loss: 0.0311 - accuracy: 0.9889
Epoch 7/50
91/91 [==============================] - 0s 2ms/step - loss: 0.0466 - accuracy: 0.9821
Epoch 8/50
91/91 [==============================] - 0s 2ms/step - loss: 0.0312 - accuracy: 0.9887
Epoch 9/50
91/91 [==============================] - 0s 2ms/step - loss: 0.0617 - accuracy: 0.9784
Epoch 10/50
91/91 [==============================] - 0s 2ms/step - loss: 0.0264 - accuracy: 0.9912
Epoch 11/50
91/91 [